### ISSUE TITLE
Play All and Shuffle All buttons on artist page draw on the "top tracks", not all tracks

### ISSUE THREAD

**Issue by ToxicFrog** [tamland/airsonic-refix#111]
For example, if I go to my artist page for Pendulum, it lists 5 "top tracks" and two albums containing 24 tracks between them. If I click Play All or Shuffle All, it enqueues the five tracks listed in "top tracks" rather than all 24 tracks by that artist.

I _think_ this is possible on an API level, but the stock airsonic UI doesn't seem to have an artist view, so I can't test it.

**Comment by tamland** [comment]
Not feasible currently due to api limitations
