### ISSUE TITLE
Airsonic-refix Gonic

### ISSUE THREAD

**Issue by KeenVox** [tamland/airsonic-refix#121]
Hi all,

I want to use Airsonic-refix with gonic on my raspberry pi. Gonic is running in docker and I installed Airsonic-refix with docker too, but I can't get it to start. When I try to connect to localhost:8080 I always get a "connection refused". I tried to change the ports, but I can't get it to work.
I'm quite new to docker, and I don't know what I'm missing.

Any help would be great. I used portainer to install the docker images. Gonic is working as expected.

Thanks in advance.

**Comment by sentriz** [comment]
did you try prefix the address with http://

**Comment by KeenVox** [comment]
Yes I tried http and https with local host and Ip. 
But I checked the log and it seems Airsonic trys to connect to 0.0.0.0:80 instead of 192.168.178.29 as it should.
Any ideas how to change that?

"2023/09/22 14:01:18 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)"

**Comment by sentriz** [comment]
wait, is that from the airsonicrefix logs? it looks like you shouldn't even be able to view the refix interface. also, how does your docker port mapping look for the refix container?

**Comment by KeenVox** [comment]
No, those are log files protainer gives me for the docker container of refix.

I can't view the interface. The ports are mapped for 8080. I tried other
ports, but it didn't work either...

Am 22. September 2023 21:52:27 schrieb Senan Kelly ***@***.***>:

**Comment by KeenVox** [comment]
Okay, I was an idiot. Got it to work. Gonic listened to the same port as airsonic and there was an conflict with that.

Now it works fine! :)
