### ISSUE TITLE
Is it possible to bypass the login page and just pass the auth as basic auth?

### ISSUE THREAD

**Issue by ajmcateer** [tamland/airsonic-refix#127]
I am using Authentik to manage my auth and it would be nice if I could have authentik log me in instead of having to put my Authentik password and then the airsonic password.

Is it possible to get the auth from the headers in the get request and bypass the login page completely?

**Comment by tamland** [comment]
Perhaps suggest this in [OpenSubsonic](https://github.com/opensubsonic/open-subsonic-api)
