### ISSUE TITLE
Support for ARM/ARM64

### ISSUE THREAD

**Issue by TheFlatworm** [tamland/airsonic-refix#18]
Would ARM64 support be possible?

**Comment by SteveDinn** [comment]
It's totally possible, you can build an ARM/ARM64 container yourself, as long as you have docker.

Run the following commands to build your own image on whatever architecture you're on:
```
    git clone https://github.com/tamland/airsonic-frontend.git
    cd airsonic-frontend
    docker run --rm -it -v $(pwd):/source node /bin/bash
```
Then, inside the `node` container:
```
     cd /source
     yarn install
     yarn build
     exit
```
Now that we have the app built, we can build the container:
```
    docker build -t tamland/airsonic-frontend -f ./docker/Dockerfile --no-cache .
```

Then to run a container based on that just-built image:
```
    docker run -p [YOUR-LOCAL-PORT]:80 tamland/airsonic-frontend
```

**Comment by TheFlatworm** [comment]
I'm a bit of a noob with this - is there a way to run a docker container that I can build in so that i don't mess up my server (Odroid)?  The server is live and would rather load the build tools in a container so i can dump everything clean if I mess up.

**Comment by SteveDinn** [comment]
That is exactly what I have given you in the comment above.

**Comment by SteveDinn** [comment]
I suppose you could also download the zip file:
```
https://github.com/tamland/airsonic-frontend/archive/master.zip
```
And just unzip that to the "source" folder as well.

**Comment by TheFlatworm** [comment]
Ah - i kind of see now, it's slowly sinking in - thank you!  I will give this a try.  Thank you so much for your help.

**Comment by tamland** [comment]
Happy to include this in the CI build if it's possible :man_shrugging:

**Comment by SteveDinn** [comment]
I'm not sure how this works if you are trying to cross-compile for a different architecture. I performed those steps on an ARM64 machine (an RPi 4) to get an ARM64 image

**Comment by TheFlatworm** [comment]
With your instructions built fine for ARM64 - thank you!

**Comment by sabinM1** [comment]
For people trying to run this now, a package, `eslint-import-resolver-webpack` doesn't support node 17, getting an incompatible module error when doing `yarn install`:
```
error eslint-import-resolver-webpack@0.13.1: The engine "node" is incompatible with this module. Expected version "^16 || ^15 || ^14 || ^13 || ^12 || ^11 || ^10 || ^9 || ^8 || ^7 || ^6". Got "17.0.1"
error Found incompatible module.
```
To get it working, just downgrade node to 16: **`docker run --rm -it -v $(pwd):/source node:16-bullseye /bin/bash`** instead of `docker run --rm -it -v $(pwd):/source node /bin/bash` from [SteveDinn's comment](https://github.com/tamland/airsonic-refix/issues/18#issuecomment-724387191). The rest of the commands are working as expected.
