### ISSUE TITLE
[Feature request] add media folder handling

### ISSUE THREAD

**Issue by johann1525** [tamland/airsonic-refix#27]
Currently i have multiple folders/libraries with different audio material. E.g. one for musik one for audio books. In the stock UI it is perfectly possible to only show content from one directory and hide the other. 

Second i like to browse my libraries by folder rather media tag. An option to switch like in the original UI and maybe enable list view instead of tiled for long lists would be fantastic.

**Comment by ToxicFrog** [comment]
#108 adds a basic form of this feature and I've been testing it locally. It's missing some features from the stock ui (play-all/play-random for anything above a single folder, displaying album art when present in a folder) but seems to be working ok otherwise.
