### ISSUE TITLE
Doesn't work with Ampache

### ISSUE THREAD

**Issue by DouglasKreider** [tamland/airsonic-refix#43]
When I try to connect this to an Ampache server, it throws an error. Ampache uses the Subsonic API, and I assume this does as well. Is there anything I can do to get this to work?

**Comment by tamland** [comment]
I assume you have followed this: https://github.com/ampache/ampache/wiki/API ?

**Comment by DouglasKreider** [comment]
The problem seems to be related to the authentication method. The other Subsonic UI I used authenticated with a username and password. This one authenticates with a token, and is not getting a valid response back from Ampache. This page, https://github.com/ampache/ampache/wiki/subsonic, mentions that there are some differences in the Ampache token authentication.

**Comment by DouglasKreider** [comment]
I was able to fix this by changing the authentication and downgrading the API version. I don't think those are changes I should push back to the repo.
