### ISSUE TITLE
"Albums" vs "CDs"

### ISSUE THREAD

**Issue by khannurien** [tamland/airsonic-refix#55]
Hi tamland,

Thanks for your hard work. I've deployed airsonic-refix with the latest Docker image:

```
Build: 3d1febf239100222d9da9aafa32ae776d27e3ba6
Build date: 2022-01-01
```

airsonic-refix seems to group albums differently than airsonic-advanced's default frontend. Example:

![image](https://user-images.githubusercontent.com/31770422/148648439-91b38093-090e-477c-b9a4-7e435d88b6a4.png)

![image](https://user-images.githubusercontent.com/31770422/148648449-a746b699-697a-4051-8388-909fec043596.png)

Is that expected?
I'll be glad to help investigate further.

Here's [a dump of the tags](https://gist.github.com/khannurien/94dbd84c3bcc0f9a182d5363d6d77245) from folders `Compilations - 2014 - Bromance/CD{1,2}`.

Best,
Vincent

**Comment by tamland** [comment]
Hi! I would report this at [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced) as airsonic-refix just display what is returned by the API. Other clients will likely display exactly the same. The default frontend doesn't actually use the API, that's probably why it's different.

However, if you properly tag albums with disc number and set the "album artist" tag, multi-disc albums should display as a single album like this:

![bilde](https://user-images.githubusercontent.com/148836/148652710-e9ce29f0-8176-4d7b-aff3-1af115113777.png)
