### ISSUE TITLE
refix group by "album artist" instead of "album" tag

### ISSUE THREAD

**Issue by hasamba** [tamland/airsonic-refix#57]
i see that someone else posted the [same issue](https://github.com/tamland/airsonic-refix/issues/55) and it was closed but i want to explain more...

i have the same problem and after checking i found out that airsonic-advanced unite the albums by "album" tag and refix by "album artist",
that's why compilation albums that were tagged with same album name for all files but different album artist (should correctly be "various artists") will show correct in airsonic but will show as seperate albums in refix.
it will be great if we can change the unity manualy (can also be by folder) or hard coded.

thanks

refix:
![image](https://user-images.githubusercontent.com/7392290/152968394-1b7ee6dd-e9d4-4059-8809-40af74c46de6.png)

airsonic-advanced
![image](https://user-images.githubusercontent.com/7392290/152968519-6932f574-de53-4573-9463-51a1c8e22fc6.png)

**Comment by tamland** [comment]
As explained refix simply displays whatever is returned from the api. Unfortunately there is nothing that can be done in the frontend to group albums differently. This has to be fixed in airsonic-advanced.
