### ISSUE TITLE
[Bug] Title Numbers counting

### ISSUE THREAD

**Issue by DoM1niC** [tamland/airsonic-refix#65]
![grafik](https://user-images.githubusercontent.com/1436958/161429291-5dcfc60a-aba0-4e42-8d91-3b4cf83bc792.png)
Fallback to count entries for TrackID if IDTag is unavailable

**Comment by DoM1niC** [comment]
fixed by https://github.com/tamland/airsonic-refix/commit/a247035afbfba804ebc189edf4c338ea45e97d52

**Comment by tamland** [comment]
Fixed on album page but not all views such at playlist and queue are able to 'guess' the correct track number and will use a different fallback instead
