### ISSUE TITLE
[Bug] Special Chars in Search no result (Blank Page)

### ISSUE THREAD

**Issue by DoM1niC** [tamland/airsonic-refix#67]
## Work
![grafik](https://user-images.githubusercontent.com/1436958/161435601-35a48373-c612-4b02-8132-fde3d5971986.png)
#### search?q= Blank searchbar show a blank page too and I think a urlencode is needed or I'm wrong -> ?q=! 
![grafik](https://user-images.githubusercontent.com/1436958/161435606-f7382ba7-1398-4fd8-aadc-e9ff7f50de8b.png)

**Comment by tamland** [comment]
I don't think the issue is in the client. The query should be encoded and decoded before getting passed to backed. If it doesn't return the expected result you should report it to [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced).

**Comment by DoM1niC** [comment]
> I don't think the issue is in the client. The query should be encoded and decoded before getting passed to backed. If it doesn't return the expected result you should report it to [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced).

indeed I switched now from Subsonic to Navidrome and your UI still working 👍🏻 and fixed the search...
