### ISSUE TITLE
Does not load HD album covers

### ISSUE THREAD

**Issue by AvMavs** [tamland/airsonic-refix#71]
For my subsonic Navidrome library, most songs have 1000 x 1000 covers (in the metadata). The software refuses to load them entirely.

**Comment by tamland** [comment]
Airsonic refix use the album covers that are provided by the subsonic API. If they aren't loading you will have to report this issue to Navidrome.

**Comment by AvMavs** [comment]
They load on every other Subsonic client I use, though.
