### ISSUE TITLE
Can't log in using airsonic-advanced

### ISSUE THREAD

**Issue by prayujt** [tamland/airsonic-refix#73]
Trying to log in prints this to the console:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://prayujt.com:4040/rest/ping?u=prayuj&s=.... (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
I'm not using any reverse proxy (nginx, apache) to run airsonic-advanced itself.

**Comment by tamland** [comment]
CORS headers are controlled by the backend not frontend. Are you running a recent version of airsonic-advanced? Also, this error message can be a symptom of a different error causing the server at the requested url to not include the proper headers.
