### ISSUE TITLE
404 refreshing tab / navigating direct to URL

### ISSUE THREAD

**Issue by antgel** [tamland/airsonic-refix#74]
Thanks for a great project. Works great on my Firefox on Android. However when I come back to the tab after some time and Firefox reloads the tab, I get a 404 and have to delete the URL path after the server name and reload everything.

**Comment by tamland** [comment]
You need to set your hosting server to fallback to `index.html` since this is a single page application. If you use the docker image no changes should be necessary.

**Comment by antgel** [comment]
Oops, absolutely correct (I am hosting as a static nginx site). Indeed, I applied the relevant part of the configuration from Docker (`try-files`) and all Is good. Thank you!
