### ISSUE TITLE
"Could not log in. (Failed to fetch)" error

### ISSUE THREAD

**Issue by volcs0** [tamland/airsonic-refix#78]
I have Airsonic-refix running on my unRAID server in a Docker container. It points to Navidrome running on the same server. Internally (local IPs), everything works great. 

I use Swag/NGINX to route 443 traffic from the outside for most of my apps - Plex, Emby, etc. When I set it up for Airsonic-refix, I indeed get the login screen, but when I enter credentials, I get the error, "Could not log in. (Failed to fetch). 
https://imgur.com/a/D4GPp8w

I'm using the latest version of both Docker containers. As I said, everything works internally with local IPs. My other containers accessed from the outside (through Cloudflare) work fine.

Thoughts?

**Comment by tamland** [comment]
It could be multiple issues. You need to check the browser console for the actual error message.

**Comment by volcs0** [comment]
Thanks. It had to do with http vs https for my Navirdome install. Works now. Thanks for the tip.
