### ISSUE TITLE
Fails to play back due to "format=raw" disregarding transcoding requirements.

### ISSUE THREAD

**Issue by cortices** [tamland/airsonic-refix#84]
When testing the web app hosted on Netlify before deploying myself, I would get "media not suitable" errors.

Opening the web console, I found the attempted playback links, and opened separately, which gave an error that "No video with supported format and MIME type found."

On a limb, I tried changing the `format=raw` parameter in the playback URL. Instantly the browser downloaded the file just fine to play.

Is there a reason the airsonic-refix app is expecting a 'raw' format file when I've configured transcoding on the backend? My files are mostly Apple Lossless, which isn't supported by browser local playback.

**Comment by tamland** [comment]
Should work now

**Comment by cortices** [comment]
Thanks! Confirming it worked great all day today, and didn’t have any issues dropping out like I’ve had from the default navidrome web interface either.
