### ISSUE TITLE
[Bug/Feature Request] Shuffle favourites tracks

### ISSUE THREAD

**Issue by LeoSum8** [tamland/airsonic-refix#91]
When playing all favourite tracks, there is no way to shuffle playback order.

Not sure if this is a bug or a missing feature :)

**Comment by tamland** [comment]
If you have suffle enabled first anything you play will be added to queue in random order. Maybe it's not so obvious..

**Comment by LeoSum8** [comment]
Ah, got it!
This indeed works, thank you!
So the playlist under "Playing" will always be progresst in consecutive order, I can only influence the order before adding anything.
