### ISSUE TITLE
[Bug] Artist page fails to render if getTopSongs errors

### ISSUE THREAD

**Issue by jprjr** [tamland/airsonic-refix#99]
Hi there -

I'm using airsonic-refix with gonic as a backend.

I enabled last.fm integration in Gonic. When calling `getTopSongs` - it seems that Gonic can return an error response if it can't locate the artist on last.fm, or has some other issue with connecting last.fm results with tracks. Either way, it returns error code `70` (data not found).

This causes airsonic-refix to throw an error and the artist page never renders - it just displays the loading icon.

**Comment by sentriz** [comment]
I also noticed this. gonic should probably also be updated to return an empty list or something . need to see what the spec says

**Comment by tamland** [comment]
Would be best if server can return empty list. I can work around it client side, but I am unable to test it as it requires setting up a last.fm account.. Without enabling last.fm gonic always returns 200 ok.

**Comment by sentriz** [comment]
@tamland @jprjr 

i just updated gonic to return an empty list instead of err code 70 when there's no results. no idea if that is to-spec or not but at least it has fixed the issue for me
